#!/bin/bash
#
# sets $AFP which is required by the isabelle theoreis
#
# If you are on windows:
#  find Cygwin-Terminal.bat in your Isabelle folder
#  $ export AFP=~/path/to/topoS/isabelle_afp
#  $ isabelle jedit
#
# If you are on MacOS, I heared that the dirname command fails. Please report bugs!
# 

TOPOS_HOME="$(readlink -f "$(pwd)/$(dirname "$0")")"

echo "setting TOPOS_HOME to: $TOPOS_HOME"

cd "$TOPOS_HOME"

export AFP="${TOPOS_HOME}/isabelle_afp"

#ISABELLE="isabelle"
ISABELLE="/home/diekmann/Downloads/Isabelle2016-RC3/bin/isabelle"

if sh -c "$ISABELLE version" | grep 'Isabelle2016'; then
    echo "Isabelle 2016"
else
    echo "Isabelle 2016 is required"
    exit -1
fi

#RC3 fix
#$ISABELLE build -d $AFP -v -b Collections
$ISABELLE jedit -d $AFP -l Automatic_Refinement #Collections
