#!/bin/bash
#
# sets $AFP which is required by the isabelle theoreis
#
# If you are on windows:
#  find Cygwin-Terminal.bat in your Isabelle folder
#  $ export AFP=~/path/to/topoS/isabelle_afp
#  $ isabelle jedit
#
# If you are on MacOS, I heared that the dirname command fails. Please report bugs!
# 

TOPOS_HOME="$(readlink -f "$(pwd)/$(dirname "$0")")"

echo "setting TOPOS_HOME to: $TOPOS_HOME"

cd "$TOPOS_HOME"

export AFP="${TOPOS_HOME}/isabelle_afp"

ISABELLE="/home/diekmann/Downloads/Isabelle2015-RC1/bin/isabelle"

if $ISABELLE version | grep 'Isabelle2015-RC1: April 2015'; then
    echo "Isabelle 2015"
else
    echo "Isabelle 2015 is required"
    exit -1
fi

#$ISABELLE build -d isabelle_afp/ -b Collections &&
#$ISABELLE jedit -d isabelle_afp/ -l Collections
#collections does not load ATM, waiting for new version
$ISABELLE jedit -d isabelle_afp/ -l Collections
